// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace UK_GameplayTags
{
	namespace Input
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Look);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jump);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ZoomIn);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ZoomOut);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(NomalSkill);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(UltimateSkill);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouch);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ToggleMouse);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Setting);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(LockOnToggle);
	}

	namespace Weapon
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponRoot);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DefaultWeapon);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dagger);
	}

	namespace Action
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Swap1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Swap2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Swap3);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(LightAttack);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyAttack);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(AirAttack);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DropAttack);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(OnGroundAttack);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Parry);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Parrying);
	}

	namespace Attack
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attacking);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Next);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitCheck);
	}

	namespace Status
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dead);
	}
	namespace Data
	{
		namespace Damages
		{
			namespace OneHandSword
			{
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Light1);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Light2);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Light3);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Light4);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Heavy1);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Heavy2);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Heavy3);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Heavy4);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Air1);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Air2);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Air3);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Air4);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(Drop);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(NormalSkill);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(UltimateSkill);
				
			}
		}
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
	}

	namespace CoolDown
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(NomalSkill);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(UltimateSkill);
	}

	namespace Food
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(FoodRoot);
	}

	namespace Material
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaterialRoot);
	}
}
