;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Boss.Enrage",NewTagName="Boss.Boss.Phase.Enrage")
+GameplayTagRedirects=(OldTagName="Boss.Boss.Phase.Enrage",NewTagName="Boss.Boss.Phase.Phase.Enrage")
+GameplayTagRedirects=(OldTagName="Boss.Phase2",NewTagName="Boss.Phase2")
+GameplayTagRedirects=(OldTagName="Boss.Phase1",NewTagName="Boss.Phase.Enrage")
+GameplayTagRedirects=(OldTagName="Boss.Phase3",NewTagName="Boss.Phase.Phase3")
+GameplayTagList=(Tag="Boss.Phase.Enrage",DevComment="")
+GameplayTagList=(Tag="Boss.Phase.Phase1",DevComment="")
+GameplayTagList=(Tag="Boss.Phase.Phase2",DevComment="")
+GameplayTagList=(Tag="Boss.Phase.Phase3",DevComment="")
+GameplayTagList=(Tag="Input.Default.ToggleMouse",DevComment="")

